name: Matt Harzewski
url: http://matt.harzewski.com
description: Something witty would go here

permalink: /:year/:month/:day/:title/

plugins: [jekyll-paginate]

paginate: 10
highlighter: true
#markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

gallerytag:
    dir: images/galleries
    url: /images/galleries
    thumb_width: 150
    thumb_height: 150
    columns: 4
